-- SQL Script for creating the products table in Supabase
-- Esegui questo script nell'SQL Editor di Supabase per configurare il database.

-- SE HAI GIÀ UNA TABELLA ESISTENTE, ESEGUI SOLO QUESTO COMANDO PER AGGIORNARE LO SCHEMA SENZA PERDERE DATI:
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS prezzo_fornitore NUMERIC DEFAULT NULL;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  squadra TEXT NOT NULL,
  categoria TEXT NOT NULL,
  versione TEXT NOT NULL,
  stagione TEXT NOT NULL,
  prezzo NUMERIC DEFAULT 23.99,
  prezzo_fornitore NUMERIC DEFAULT NULL,
  immagine TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- (Opzionale) Se desideri abilitare Row Level Security (RLS) ma consentire la lettura pubblica:
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Consenti lettura pubblica" ON products FOR SELECT USING (true);
-- CREATE POLICY "Consenti inserimento pubblico" ON products FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Consenti modifica pubblica" ON products FOR UPDATE USING (true);
-- CREATE POLICY "Consenti eliminazione pubblica" ON products FOR DELETE USING (true);

-- --------------------------------------------------------
-- Tabella per le regole dei prezzi (matrice Categoria + Target)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS price_rules (
  categoria TEXT NOT NULL,
  target TEXT NOT NULL,
  prezzo NUMERIC NOT NULL,
  PRIMARY KEY (categoria, target)
);

-- --------------------------------------------------------
-- Tabella per il catalogo delle squadre (Club, Nazionali, NBA)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  categoria TEXT NOT NULL,
  sezione TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- Tabella per la registrazione degli ordini
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  telefono TEXT NOT NULL,
  squadra TEXT NOT NULL,
  personalizzazione TEXT,
  taglia TEXT,
  totale TEXT NOT NULL,
  foto TEXT,
  prezzo_fornitore TEXT,
  costo_prodotti_usd TEXT,
  costo_spedizione_usd TEXT,
  costo_totale_usd TEXT,
  cambio_usd_eur TEXT,
  costo_totale_eur TEXT,
  profitto_eur TEXT,
  is_archived BOOLEAN DEFAULT FALSE,
  lotto_id INT DEFAULT NULL,
  carrello JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Aggiungi vincolo di chiave esterna tra orders e lotti per garantire l'integrità dei dati
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_constraint 
        WHERE conname = 'fk_orders_lotto_id'
    ) THEN
        ALTER TABLE orders 
        ADD CONSTRAINT fk_orders_lotto_id 
        FOREIGN KEY (lotto_id) 
        REFERENCES lotti(id) 
        ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_orders_data ON orders(data);
CREATE INDEX IF NOT EXISTS idx_orders_lotto_id ON orders(lotto_id);

-- --------------------------------------------------------
-- Tabella per la cronologia dei lotti archiviati
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS lotti (
  id INT PRIMARY KEY,
  numero_lotto TEXT NOT NULL,
  archived_at TEXT NOT NULL,
  numero_ordini INT NOT NULL,
  numero_articoli INT NOT NULL,
  incasso_totale_eur NUMERIC NOT NULL,
  costo_prodotti_usd NUMERIC NOT NULL,
  costo_spedizione_usd NUMERIC NOT NULL,
  costo_totale_usd NUMERIC NOT NULL,
  costo_totale_eur NUMERIC NOT NULL,
  profitto_eur NUMERIC NOT NULL,
  margine_percentuale NUMERIC NOT NULL,
  excel_url TEXT,
  orders JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- Tabella per le impostazioni e configurazioni generiche
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- --------------------------------------------------------
-- Tabella per la Wishlist dei clienti
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  product_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  CONSTRAINT unique_user_product UNIQUE(user_id, product_id)
);

-- Abilita Row Level Security (RLS) per sicurezza
ALTER TABLE customer_wishlist ENABLE ROW LEVEL SECURITY;

-- Criteri di accesso RLS per la Wishlist
CREATE POLICY "Gli utenti possono gestire la propria wishlist" ON customer_wishlist
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- --------------------------------------------------------
-- Tabella per le conversazioni della chat di assistenza
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_conversations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID UNIQUE,
  nome TEXT,
  email TEXT,
  stato TEXT DEFAULT 'Nuova',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  last_message_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- Tabella per i messaggi della chat di assistenza
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id UUID REFERENCES chat_conversations(id) ON DELETE CASCADE,
  sender TEXT NOT NULL,
  message TEXT,
  attachment_url TEXT,
  attachment_type TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- --------------------------------------------------------
-- Tabella per i codici sconto (Coupon)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS coupon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL, -- 'percentuale', 'fisso', 'fornitore'
  value NUMERIC DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  usage_limit INT DEFAULT NULL,
  used_count INT DEFAULT 0,
  expires_at DATE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Aggiunta colonne coupon alla tabella orders per storico ordini
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code TEXT DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_discount NUMERIC DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_type TEXT DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_value NUMERIC DEFAULT NULL;

-- Aggiunta colonne coupon alla tabella customer_orders per visualizzazione cliente
ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS coupon_code TEXT DEFAULT NULL;
ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS coupon_discount NUMERIC DEFAULT NULL;
-- --------------------------------------------------------
-- Tabella per le Recensioni dei Clienti (Verificate ed Esperienze Condivise)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID DEFAULT NULL,
  customer_name TEXT NOT NULL,
  email TEXT DEFAULT NULL,
  order_id BIGINT DEFAULT NULL,
  order_number TEXT DEFAULT NULL,
  product_id TEXT DEFAULT NULL,
  product_name TEXT DEFAULT NULL,
  product_image TEXT DEFAULT NULL,
  purchase_date TEXT DEFAULT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title TEXT DEFAULT NULL,
  comment TEXT NOT NULL,
  images JSONB DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  review_type TEXT NOT NULL DEFAULT 'shared_experience' CHECK (review_type IN ('verified_purchase', 'shared_experience')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_status ON reviews(status);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON reviews(product_id);

-- Policy RLS per recensioni
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Consenti lettura recensioni approvate" ON reviews FOR SELECT USING (true);
CREATE POLICY "Consenti inserimento recensioni" ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Consenti modifica recensioni" ON reviews FOR UPDATE USING (true);
CREATE POLICY "Consenti eliminazione recensioni" ON reviews FOR DELETE USING (true);

-- --------------------------------------------------------
-- Bucket Storage 'reviews' per le Foto delle Recensioni
-- (Eseguire nella SQL Editor di Supabase per abilitare il bucket 'reviews')
-- --------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('reviews', 'reviews', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy RLS per il bucket storage 'reviews'
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Foto recensioni pubbliche in lettura'
  ) THEN
    CREATE POLICY "Foto recensioni pubbliche in lettura" ON storage.objects FOR SELECT USING (bucket_id = 'reviews');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Consenti upload foto recensioni'
  ) THEN
    CREATE POLICY "Consenti upload foto recensioni" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'reviews');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Consenti modifica foto recensioni'
  ) THEN
    CREATE POLICY "Consenti modifica foto recensioni" ON storage.objects FOR UPDATE USING (bucket_id = 'reviews');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Consenti eliminazione foto recensioni'
  ) THEN
    CREATE POLICY "Consenti eliminazione foto recensioni" ON storage.objects FOR DELETE USING (bucket_id = 'reviews');
  END IF;
END $$;

-- --------------------------------------------------------
-- Sezione Suddivisione Conti (Sergio & Riccardo)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS profit_shares (
  id BIGSERIAL PRIMARY KEY,
  order_id TEXT UNIQUE NOT NULL,
  profit_total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  sergio_percentage NUMERIC(5, 2) NOT NULL DEFAULT 50,
  riccardo_percentage NUMERIC(5, 2) NOT NULL DEFAULT 50,
  sergio_initial_share NUMERIC(10, 2) NOT NULL DEFAULT 0,
  riccardo_initial_share NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profit_share_movements (
  id BIGSERIAL PRIMARY KEY,
  profit_share_id TEXT NOT NULL,
  order_id TEXT NOT NULL,
  recipient TEXT NOT NULL CHECK (recipient IN ('sergio', 'riccardo', 'shared')),
  type TEXT NOT NULL DEFAULT 'completino',
  amount NUMERIC(10, 2) NOT NULL,
  sergio_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  riccardo_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profit_shares ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Consenti tutto profit_shares" ON profit_shares FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE profit_share_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Consenti tutto profit_share_movements" ON profit_share_movements FOR ALL USING (true) WITH CHECK (true);
